#!/usr/bin/env Rscript
#args <- commandArgs(trailingOnly=TRUE)

```{r}
    
get_mode <- function(v){
    uniqv <- unique(v)
    res <- uniqv[which.max(tabulate(match(v, uniqv)))]
    return(res)
}


library(plyr)
library(survival)
library(R.matlab)
library(glmnet)
library(groupdata2)
library(doParallel)
library(readxl)
# library(impute)
#library(survcomp)
#registerDoParallel(cores=4)

outcome = "Intracranial_Hemorrhage"

base_folder <-paste("C:/directory/",outcome, sep="")

Ncv <- 5
model_type <- 'CoxPH_CompetingRisk'
random_state <- 2021

feautre_type <- ''
with_AHI <- FALSE
result_path <- base_folder

# get data
df <- read.csv(file.path(base_folder, 'tr_curves.csv'))
print(dim(df))
df$id <- 1:nrow(df)

df_AJ <- df
df_AJ$event <- factor(df_AJ$event, 0:2, labels=c("censor", "event1", "event2"))
AJ_fit <- survfit(Surv(duration, event) ~ 1, data=df_AJ, id=id)

# get X and y names
ynames <- c('duration', 'event')

Features <- read.csv(paste(base_folder, sprintf('/full_feat_list.csv'), sep=""))


Features  <- subset(Features, Features$X0 != 'Weight')
Features  <- subset(Features, Features$X0 != 'Height')
Features  <- subset(Features, Features$X0 != 'DiastolicBP')
Features  <- subset(Features, Features$X0 != 'HeartRate')
Features  <- subset(Features, Features$X0 != 'Temperature')
Features  <- subset(Features, Features$X0 != 'HDL')
Features  <- subset(Features, Features$X0 != 'LDL')
Features  <- subset(Features, Features$X0 != 'AST')

xnames <- Features$X0

must_have_names <- c('Age', 'Female')
xnames <- xnames[!(xnames%in%must_have_names)]

# generate outer CV ids
set.seed(random_state)
mrns <- unique(df$MRN)
outer_cv_mrn_foldid <- as.numeric(fold(as.data.frame(1:length(mrns)), Ncv)$.folds)
names(outer_cv_mrn_foldid) <- mrns
outer_cv_foldid <- c()
for (i in 1:nrow(df))
    outer_cv_foldid <- c(outer_cv_foldid, outer_cv_mrn_foldid[[toString(df$MRN[i])]])
#write.csv(outer_cv_foldid, file.path(base_folder, sprintf('outer_cv_foldid_%s.csv', outcome)), row.names=FALSE)

best_alphas <- c()
for (cvi in 1:(Ncv+1)) {
    if (cvi<=Ncv) {
        trids <- outer_cv_foldid!=cvi
        teids <- outer_cv_foldid==cvi
        alphas <- c(0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9)
    } else {  # last cv is training all data
        trids <- outer_cv_foldid>0   # all
        teids <- outer_cv_foldid==0  # empty
        alphas <- c(get_mode(best_alphas))
    }
    dftr <- df[trids,]
    dfte <- df[teids,]

    dftr[,'event2'] <- dftr[,'event']
    dftr[dftr[,'event2']==2, 'event2'] = 0
    ytr <- Surv(dftr[,'duration'], dftr[,'event2'])

    
    if (feautre_type!='baseline') {
        # fit a Cox ElasticNet model to reduce dimension 
        Xtr <- as.matrix(dftr[,xnames])
        foldid <- as.numeric(fold(as.data.frame(1:nrow(dftr)), Ncv)$.folds)
        best_cvm <- -Inf
        models <- c()
        for (i in 1:length(alphas)) {
            print(alphas[i])
            coxph_fit <- cv.glmnet(Xtr, ytr, family='cox', type.measure='C', foldid=foldid, alpha=alphas[i], parallel=TRUE)
            cvm <- coxph_fit$cvm[coxph_fit$index['min',]]
            if (cvm>best_cvm) {
                best_cvm <- cvm
                best_alpha <- alphas[i]
                best_index <- i
            }
            models <- c(models, list(coxph_fit))
        }
        coxph_fit <- models[[best_index]]
        print(alphas[best_index])
        
        coef_ <- as.numeric(coef(coxph_fit, s=coxph_fit$lambda[coxph_fit$index['min',]]))
        s=coxph_fit$lambda[coxph_fit$index['min',]]
        best_alphas <- c(best_alphas, alphas[best_index])
    }

    # fit competing risk model with selected features
    if (feautre_type!='baseline') {
        xnames2 <- c(xnames[abs(coef_)>0], must_have_names)
    } else {
        xnames2 <- c('Age', 'Sex')
    }
    formula_ <- as.formula(paste('Surv(duration, event)~', paste(xnames2, collapse = "+")))
    dftr$event <- factor(dftr$event, 0:2, labels=c("censor", "event1", "event2"))
    coxph_fit <- coxph(formula_, data=dftr, id=id, ties='breslow')
    
    coxph_fit_summary <- summary(coxph_fit)
    coxph_coef <- cbind(coxph_fit_summary$coefficients, coxph_fit_summary$conf.int)
    
    # save predicted z
    zptr1 <- drop(as.matrix(dftr[,xnames2])%*%coxph_coef[1:(nrow(coxph_coef)/2),'coef'])
    zptr2 <- drop(as.matrix(dftr[,xnames2])%*%coxph_coef[(nrow(coxph_coef)/2+1):nrow(coxph_coef),'coef'])
    names(zptr1) <- NULL
    names(zptr2) <- NULL
    
    # save coefficients
    write.csv(coxph_coef, file.path(result_path, sprintf('coef_%s_%s.csv', outcome, model_type)))
    saveRDS(list(coxph_fit, dftr), file.path(result_path, sprintf('model_%s_%s.rda', outcome, model_type)))
    
    writeMat(file.path(result_path, sprintf('results_%s_%s_cv%d.mat', outcome, model_type, cvi)), cindex_tr=coxph_fit_summary$concordance, transition=coxph_fit$transition, Xnames=c(xnames,'Age', 'Sex'), Xnames2=xnames2, coef=coxph_coef, zptr1=zptr1, zptr2=zptr2, best_l1_ratio=alphas, Xtr=Xtr) 
}



dfte <- read.csv(file.path(base_folder, 'te_curves.csv'))
dfte$id <- 1:nrow(dfte)
Xte <- as.matrix(dfte[,xnames2])

zpte1 <- drop(as.matrix(Xte)%*%coxph_coef[1:(nrow(coxph_coef)/2),'coef'])
names(zpte1) <- NULL

yp <-survfit(coxph_fit, dfte)

writeMat(file.path(result_path, sprintf('coxph_scores_%s.mat', outcome)),
         survtime=yp$time, survprob=yp$pstate, survstates=yp$states)

# get survival curves
zmean <- mean(zpte1)
zstd <- sd(zpte1)
zmean_m_std <- zmean - zstd
zmean_p_std <- zmean + zstd
zperc <- quantile(zpte1, c(0,0.005,0.01,0.025,0.1,0.25,0.5,0.75,0.9,0.975,0.99,0.995,1))
zs <- c(mean=zmean, mean_m_std=zmean_m_std, mean_p_std=zmean_p_std, zperc)
idx <- sapply(zs,function(x) which.min(abs(zpte1-x)))
yp <-survfit(coxph_fit, dfte[idx,])

writeMat(file.path(result_path, sprintf('survival_curves_te_%s.mat', outcome)),
         survtime=yp$time, survprob=yp$pstate, survstates=yp$states)


# get AJ curves
for (i in 1:3) {
  if (i==1) {
    this_data <- 'mean'
    target_z <- zmean
  } else if (i==2) {
    this_data <- 'mean-std'
    target_z <- zmean_m_std
  } else if (i==3) {
    this_data <- 'mean+std'
    target_z <- zmean_p_std
  }
  idx <- (zpte1>=target_z - zstd/3) & (zpte1<=target_z + zstd/3)
  df_AJ <- dfte[idx,]
  df_AJ$event <- factor(df_AJ$event, 0:2, labels=c("censor", "event1", "event2"))
  AJ_fit <- survfit(Surv(duration, event) ~ 1, data=df_AJ, id=id)
  writeMat(file.path(result_path, sprintf('AJ_output_te_%s_%s.mat', outcome, this_data)), time=AJ_fit$time, val=AJ_fit$pstate, lower=AJ_fit$lower, upper=AJ_fit$upper, states=AJ_fit$states)
}


print(coxph_fit_summary)
```

```{r}

dft <- read.csv(file.path(base_folder, 'tr_curves.csv'))
dft$id <- 1:nrow(dft)
Xte <- as.matrix(dft[,xnames2])

zpte1 <- drop(as.matrix(Xte)%*%coxph_coef[1:(nrow(coxph_coef)/2),'coef'])
names(zpte1) <- NULL

# get survival curves
zmean <- mean(zpte1)
zstd <- sd(zpte1)
zmean_m_std <- zmean - zstd
zmean_p_std <- zmean + zstd
zperc <- quantile(zpte1, c(0,0.005,0.01,0.025,0.1,0.25,0.5,0.75,0.9,0.975,0.99,0.995,1))
zs <- c(mean=zmean, mean_m_std=zmean_m_std, mean_p_std=zmean_p_std, zperc)
idx <- sapply(zs,function(x) which.min(abs(zpte1-x)))
yp <-survfit(coxph_fit, dft[idx,])

writeMat(file.path(result_path, sprintf('survival_curves_tr_%s.mat', outcome)),
         survtime=yp$time, survprob=yp$pstate, survstates=yp$states)


# get AJ curves
for (i in 1:3) {
  if (i==1) {
    this_data <- 'mean'
    target_z <- zmean
  } else if (i==2) {
    this_data <- 'mean-std'
    target_z <- zmean_m_std
  } else if (i==3) {
    this_data <- 'mean+std'
    target_z <- zmean_p_std
  }
  idx <- (zpte1>=target_z - zstd/3) & (zpte1<=target_z + zstd/3)
  df_AJ <- dft[idx,]
  df_AJ$event <- factor(df_AJ$event, 0:2, labels=c("censor", "event1", "event2"))
  AJ_fit <- survfit(Surv(duration, event) ~ 1, data=df_AJ, id=id)
  writeMat(file.path(result_path, sprintf('AJ_output_tr_%s_%s.mat', outcome, this_data)), time=AJ_fit$time, val=AJ_fit$pstate, lower=AJ_fit$lower, upper=AJ_fit$upper, states=AJ_fit$states)
}
```


```{r}

te_final_data <- read.csv(paste(base_folder, sprintf('/te_data_full.csv'), sep=""))


# Test competing risk model with selected features -- All test hold-out set (external validation - test data)

xte <- te_final_data

# redefine y
xte$event <- factor(xte$event, 0:2, labels=c("censor", "event1", "event2"))

# Fit survival data using the Kaplan-Meier method
y <- Surv(time = xte$duration, event = xte$event) 

# reproduce coxph.fit$concordance
zpte1 <- drop(as.matrix(xte[,xnames2])%*%coxph_coef[1:(nrow(coxph_coef)/2),'coef'])
zpte2 <- drop(as.matrix(xte[,xnames2])%*%coxph_coef[(nrow(coxph_coef)/2+1):nrow(coxph_coef),'coef'])
names(zpte1) <- NULL
names(zpte2) <- NULL
        
y <- aeqSurv(y)
y <-Surv(c(y[,1], y[,1]),c(as.integer(y[,2]==1), as.integer(y[,2]==2)))

zpte <- c(zpte1, zpte2)
istrat <- c(rep(1, length(zpte1)), rep(2,length(zpte2)))
res <- concordancefit(y, zpte, istrat, reverse=TRUE, timefix=FALSE)
cindex_te_all_hold_out <- c("C"=res$concordance, "se(C)"=sqrt(res$var))

print(cindex_te_all_hold_out)

```



```{r}

# Test competing risk model with selected features -- Bootsrapping on test hold-out set (external validation - test data)

cindexes <- c()
cindexes_se <- c()


for (iter in 0:999) {
  
  te_indexes <- read.csv(paste(base_folder, sprintf('/index/index_%d.csv', iter), sep=""))
  
  te_data <- te_final_data[te_indexes$level_1,]

  te_time <- te_data$duration

  te_label <- te_data$event


  xte <- te_data[, (names(te_data) %in% xnames2)] # vars only in list vars
  
  # reproduce coxph.fit$concordance
  zpte1 <- drop(as.matrix(xte[,xnames2])%*%coxph_coef[1:(nrow(coxph_coef)/2),'coef'])
  names(zpte1) <- NULL

         
  #for RR
  zmean <- mean(zpte1)
  zstd <- sd(zpte1)
  zmean_m_std <- zmean - zstd
  zmean_p_std <- zmean + zstd
  zperc <- quantile(zpte1, c(0,0.005,0.01,0.025,0.1,0.25,0.5,0.75,0.9,0.975,0.99,0.995,1))
  zs <- c(mean=zmean, mean_m_std=zmean_m_std, mean_p_std=zmean_p_std, zperc)
  idx <- sapply(zs, function(x) which.min(abs(zpte1-x)))
  yp <- survfit(coxph_fit, xte[idx,])
  
 
  # save curves for test
  writeMat(file.path(base_folder, sprintf('/boot/bootstrapp_te_%d.mat', iter)), zpte=zpte1, survtime=yp$time, survprob=yp$pstate, survstates=yp$states, idx=idx)

  # C-index ####
 
  
  # redefine y
  te_label <- factor(te_label, 0:2, labels=c("censor", "event1", "event2"))

  # Fit survival data using the Kaplan-Meier method
  y <- Surv(time = te_time, event = te_label) 

  # reproduce coxph.fit$concordance

  zpte1 <- drop(as.matrix(xte[,xnames2])%*%coxph_coef[1:(nrow(coxph_coef)/2),'coef'])
  zpte2 <- drop(as.matrix(xte[,xnames2])%*%coxph_coef[(nrow(coxph_coef)/2+1):nrow(coxph_coef),'coef'])
  names(zpte1) <- NULL
  names(zpte2) <- NULL
  
  y2 <- aeqSurv(y)
  y2 <-Surv(c(y2[,1], y2[,1]),c(as.integer(y2[,2]==1), as.integer(y2[,2]==2)))

  zpte <- c(zpte1, zpte2)
  istrat <- c(rep(1, length(zpte1)), rep(2,length(zpte2)))
  res <- concordancefit(y2, zpte, istrat, reverse=TRUE, timefix=FALSE)
  cindex <- res$concordance
  cindex_se <- sqrt(res$var)

  cindexes <- c(cindexes, cindex)
  cindexes_se <- c(cindexes_se, cindex_se)
  
  
  print(iter)

}


```


```{r}

# confidence intervals

ci <- function(stats) 
  {
  alpha = 0.95
  p = ((1.0-alpha)/2.0) #* 100
  lower = max(0.0, quantile(stats, p))
  p = (alpha+((1.0-alpha)/2.0)) #* 100
  upper = min(1.0, quantile(stats, p))
  
  return(list(lower, upper))
  }
        
lower_upper = ci(cindexes)

mean_cindex = mean(cindexes)
median_cindex = median(cindexes)

print(mean_cindex)
print(lower_upper)

```
